### ISSUE TITLE
change source url from goolgemap to openstreetmap

### ISSUE THREAD

**Issue by qy-yang** [gmplot/gmplot#100]
change source url from goolgemap to openstreetmap

**Comment by sandrotosi** [comment]
why @qy-yang ? this project name immediately points to google maps, and the code generation is tightly related to the gmaps APIs

you cany just change the URL and hope it works :( maybe that'd be a different project?

**Comment by frslm** [comment]
Will close since this is outside the scope of this Google-Maps-based project.

**Comment by frslm** [comment]
P.S. @qy-yang, there is another project, [folium](https://github.com/python-visualization/folium), that does Python visualization if you're looking for a library built on OpenStreetMap (and don't need Google-Maps-specific functionality).
