### ISSUE TITLE
Turn map object into html source code

### ISSUE THREAD

**Issue by elisavetliv** [gmplot/gmplot#108]
Hello! I'm trying to run  gmplot from Azure Databricks and it seems to be a really nice tool for map visualization.
The problem is that gmap.draw("my_map.html") doesn't show anything.

Is there a way to turn map object into html source code?

**Comment by vgm64** [comment]
It writes a file. Can you access the file? Or is that not possible with
Databricks?

It was a poor choice to not include a raw html draw function (but me on web
apps, but I had filesystem access).

**Comment by frslm** [comment]
Similar to #68; we should reintroduce this feature.

**Comment by frslm** [comment]
This feature was added in #139; you can now call `gmap.get()` to get the map as an HTML string.
