### ISSUE TITLE
Marker does not work after it marks 256 points. And it wipes out all the marks.

### ISSUE THREAD

**Issue by satnaik** [gmplot/gmplot#117]
I am trying to mark a bunch of points on the map and observed that after a certain point it stops marking and wipes out all the previously marked points. I debugged the gmplot.py module and saw that when the length of array exceeds 256 this issue is coming in to picture.

**Comment by frslm** [comment]
@satnaik I couldn't reproduce this on my end; I was able to place 500 markers on a map without issue - could you share a code snippet that shows this issue?

**Comment by frslm** [comment]
I'll be closing this for now since I wasn't able to reproduce this and couldn't find a code snippet or traceback that shows this issue.

If it happens again, feel free to post a code snippet or traceback and I can reopen this.
