### ISSUE TITLE
Google API Keys not accepted while using gmplot.GoogleMapPlotter.from_geocode

### ISSUE THREAD

**Issue by neerajmontu** [gmplot/gmplot#121]
Below code fails, but should work:-

import gmplot
gmap2 = gmplot.GoogleMapPlotter.from_geocode("Jonkoping, Sweden", 13)
gmap2.draw(".\\out\\map12.html")

**Root cause:**
1. from_geocode creates a new instance, and then even when API key passed during instance creation is lost while doing this.
2. http is no longer allowed by google, so geocode fails in any case.

**Fix for this (proper):**
gmplot.py:-
from_geocode should have APIKey as a new parameter.
And then cls() should use that parameter as well.
This parameter should then be extended to geocode method, and accordingly the conditioning be done for http or https in geocode.

I have tested a fix for this and works:-
   def from_geocode(cls, location_string, zoom=13, pApiKey=''):
        lat, lng = cls.geocode(location_string, pApiKey)
        return cls(lat, lng, zoom, pApiKey)

   def geocode(self, location_string, pApikey=''):
        if pApikey == '':
            geocode = requests.get(
                'http://maps.googleapis.com/maps/api/geocode/json?address="%s"' % location_string)
        else:
            geocode = requests.get(
                'https://maps.googleapis.com/maps/api/geocode/json?address="%s"' % location_string + "&key=" + pApikey)

 These two pieces shall solve it.

Regards,
Neeraj Kumar

**Comment by frslm** [comment]
This is addressed in #111; we'd just need the to maintainer to review them.

**Comment by vgm64** [comment]
Merged #111.

**Comment by frslm** [comment]
Fixed in #111.
