### ISSUE TITLE
ImportError: cannot import name '_StringWriter'

### ISSUE THREAD

**Issue by enavarro01** [gmplot/gmplot#140]
ImportError: cannot import name '_StringWriter'

**Comment by frslm** [comment]
@enavarro01, could you post the traceback here? And are you using Python 2 or 3?

To get this to run in the meantime, you can temporarily comment out that `_StringWriter` import as well as the function it's used in (`GoogleMapPlotter.get()`).

**Comment by enavarro01** [comment]
Thanks Faris.

**Comment by enavarro01** [comment]
I am using pyhton 3

**Comment by frslm** [comment]
@enavarro01, it works on my end (Python 3) as well as on this project's Python 3 test suite. Is there any other info you could provide to help us figure out what's wrong? If you pull down a fresh copy of this repo and try to run it, do you still get this issue?

**Comment by frslm** [comment]
I'll be closing this for now since I wasn't able to reproduce this and couldn't find a code snippet or traceback that shows this issue.

If it happens again, feel free to post a code snippet or traceback and I can reopen this.

**Comment by enavarro01** [comment]
Thank you
