### ISSUE TITLE
Is it possible to plot points of multiple colors on a single map?

### ISSUE THREAD

**Issue by cteodorski** [gmplot/gmplot#161]
I assumed I could call .scatter twice with two separate sets of coordinates and specify the colors in each one, but that doesn't seem to be working as expected.....

**Comment by frslm** [comment]
I tried calling `scatter()` twice with different colours and it worked on my end:
```python
from gmplot import GoogleMapPlotter

apikey = '' # (your API key here)
gmap = GoogleMapPlotter(37.766956, -122.448481, 14, apikey=apikey)

golden_gate_park_corners = zip(*[
    (37.771269, -122.511015),
    (37.773495, -122.464830),
    (37.774797, -122.454538),
    (37.771988, -122.454018),
    (37.773646, -122.440979),
    (37.772742, -122.440797),
    (37.771096, -122.453889),
    (37.768669, -122.453518),
    (37.766227, -122.460213),
    (37.764028, -122.510347)
])

attractions = zip(*[
    (37.769901, -122.498331),
    (37.768645, -122.475328),
    (37.771478, -122.468677),
    (37.769867, -122.466102),
    (37.767187, -122.467496),
    (37.770104, -122.470436)
])

gmap.scatter(*attractions, color='blue', size=40, marker=True)
gmap.scatter(*golden_gate_park_corners, color='red', size=40, marker=True)

gmap.draw('map.html')
```

![image](https://user-images.githubusercontent.com/8406475/84213478-c4ad6f80-aa8e-11ea-85a4-b9a9ecb5633c.png)

(works for both `marker=True` and `False`)

---

Could you post your code snippet if it's still not working? Also, if you're using the latest commit, you can now specify multiple colours in a single `scatter()` call.

**Comment by cteodorski** [comment]
Thank you for the quick response - I will rework my code based upon your example and see if I can get it working.

**Comment by cteodorski** [comment]
I got it working, thank you so much for your assistance.

**Comment by I-PD** [comment]
Is it possible to add a colorbar?
