### ISSUE TITLE
Crash Course Example Google Maps Loads Incorrectly with API Key

### ISSUE THREAD

**Issue by j-c-cook** [gmplot/gmplot#173]
I am using the `Crash Course` example from the readme. I have followed the instructions for creating a google API. When using the API key, I get an error. 

Here's what I see without using my generated API key:
![NoAPI](https://user-images.githubusercontent.com/39248734/87211948-b480ee00-c2e1-11ea-830c-b180429c5eca.png)

Here's what I see once I insert an API key:
![UsingAPI](https://user-images.githubusercontent.com/39248734/87211958-c06cb000-c2e1-11ea-95f7-5955569db286.png)

OS == Linux Ubuntu 20.04
python == 3.6.5
gmplot == 1.4.1

The error occurs on both Firefox and Chrome. Is this issue occurring with anyone else?

Edit: I am getting the same error on Windows 10, python 3.6.8, gmplot 1.4.1

**Comment by frslm** [comment]
Hey @j-c-cook, I'm able to see the map (with an API key) without issue on gmplot 1.4.1 and Chrome.

Since the error message is asking you to see the console for more info, could you hit F12 (on Firefox or Chrome) to open it up and show us what the error is? (Note: If the error message or screenshot contains your API key, be sure to hide it or blank it before posting here!)

**Comment by j-c-cook** [comment]
I'm getting back on this project today. I am reading more into the google api setup. Attached is a list of things google says to do. I had previously only done 2 and 3. 

Do I need to create a billing account first? Maybe I had read this somewhere. I had not done 4 last time, so I may try that before going back and creating a billing account. 

![google_api_instructions](https://user-images.githubusercontent.com/39248734/88083509-c3209e00-cb48-11ea-98ff-49bfc0ad9d71.png)

**Comment by j-c-cook** [comment]
Yes, follow the 4 steps to completion and it will work. First $300 of google api calls is free.
