### ISSUE TITLE
Marker path doesn't work on Windows

### ISSUE THREAD

**Issue by markhannon** [gmplot/gmplot#18]
I have just installed a script that works fine on OSX onto a windows box with Python27.   

When I run the script and create a HTML file it doesn't render any markers.

Looking at the Chrome console I see:
file:///C:/Python27libsite-packagesgmplotmarksers/FFA500.png 
ERR_FILE_NOT_FOUND

It seems that the path separator is incorrect and not used.

Looking at the actual HTML file the path separators are all backslashes

Changing the HTML to use forward slash as separator seems to work,

**Comment by AlanTJohnstone** [comment]
Change the following line
self.coloricon = os.path.join(os.path.dirname(__file__), 'markers/%s.png')
 in the class init definition to
self.coloricon = "http://www.googlemapsmarkers.com/v1/%s/"

**Comment by markhannon** [comment]
Looks like a good solution - also gets around the issues that the created file only works when opened on the machine it was generated from.

**Comment by eulertech** [comment]
While open the html with Google Chrome, I didn't see any markers. Here is sample output from the html:
`function initialize() {
		var centerlatlng = new google.maps.LatLng(41.059124, -71.922194);
		var myOptions = {
			zoom: 10,
			center: centerlatlng,
			mapTypeId: google.maps.MapTypeId.ROADMAP
		};
		var map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);

		var latlng = new google.maps.LatLng(-71.937142, 41.078977);
		var img = new google.maps.MarkerImage('http://www.googlemapsmarkers.com/v1/000000/');
		var marker = new google.maps.Marker({
		title: "no implementation",
		icon: img,
		position: latlng
		});
		marker.setMap(map);`
What's wrong here? Chrome can't render the markers

**Comment by derrickeckardt** [comment]
I found a simpler solution, building on AlanTJohnstone's comment.  After declaring the GoogleMapPlotter object:

`gmap=gmplot.GoogleMapPlotter(39.833333, -98.583333, 5)`

I add the following line of code into my program

`gmap.coloricon = "http://www.googlemapsmarkers.com/v1/%s/"`

And, then my markers display without a problem on any browser and platform. This has the benefit of being easy to implement and you don't have to touch the original source code.  If it gets fixed eventually in the source code, it should still work (unless the variable name changes).

**Comment by MuqadderIqbal** [comment]
@derrickeckardt This does not seem to work anymore. I even downloaded a marker image locally and tried setting the gmap.coloricon property but I get an error message. 
My sample code:
``
gmap = gmplot.GoogleMapPlotter(latList[0],lonList[0], zoom = 10)
gmap.scatter(latList, lonList,  edge_width=10)
gmap.coloricon = "marker.jpg"
gmap.draw("test.html")

and the Error message:
TypeError                                 Traceback (most recent call last)
<ipython-input-131-0aadfe9722be> in <module>()
      2 gmap.scatter(latList, lonList,  edge_width=10)
      3 gmap.coloricon = "marker.jpg"
----> 4 gmap.draw("test.html")

~/anaconda3_501/lib/python3.6/site-packages/gmplot/gmplot.py in draw(self, htmlfile)
    189         self.write_map(f)
    190         self.write_grids(f)
--> 191         self.write_points(f)
    192         self.write_paths(f)
    193         self.write_shapes(f)

~/anaconda3_501/lib/python3.6/site-packages/gmplot/gmplot.py in write_points(self, f)
    237     def write_points(self, f):
    238         for point in self.points:
--> 239             self.write_point(f, point[0], point[1], point[2], point[3])
    240 
    241     def get_cycle(self, lat, lng, rad):

~/anaconda3_501/lib/python3.6/site-packages/gmplot/gmplot.py in write_point(self, f, lat, lon, color, title)
    283                 (lat, lon))
    284         f.write('\t\tvar img = new google.maps.MarkerImage(\'%s\');\n' %
--> 285                 (self.coloricon % color))
    286         f.write('\t\tvar marker = new google.maps.Marker({\n')
    287         f.write('\t\ttitle: "%s",\n' % title)

TypeError: not all arguments converted during string formatting

**Comment by fenchu** [comment]
markerimage path gets wrong in windows:
`var img = new google.maps.MarkerImage('C:\Users\mortenb\.virtualenv\frost\lib\site-packages\gmplot\markers/FF0000.png');`

if I replace them with:
`var img = new google.maps.MarkerImage('C:\\Users\\mortenb\\.virtualenv\\frost\\lib\\site-packages\\gmplot\\markers\\FF0000.png');`

it works in google chrome, but not in firefox.

Path is fine in linux though
