### ISSUE TITLE
Does this support v3 api?

### ISSUE THREAD

**Issue by Coderx7** [gmplot/gmplot#188]
Hi, and thank you very much for all of this really appreciate it. 
I recently started working on googlemaps and I am using your module for couple of days now. 
I however noticed my map doesn't look like the one you posted as the demo, it looks like this(aside from the development warning message everywhere, there is no map/satellite toggle): 
![image](https://user-images.githubusercontent.com/5382892/133371181-6f144079-b693-4e2a-827a-3bb123617bb2.png)
and I am using an api-key. so I was searching as to why this is happening and I noticed [since may 26th 2021,](https://developers.google.com/maps/documentation/javascript/v2tov3) google has retired its v2 api and all should be using v3. 
So here I am asking whether gmplot is using v3 or not and whether my issue is caused by simply this or something else I entirely have missed here. 
Thanks a lot in advance

**Comment by frslm** [comment]
gmplot should already be on v3 of the API; I also get your screenshot when I don't use an API key, so perhaps that's the issue here? An invalid key?

**Comment by Coderx7** [comment]
Thanks you are right. all is fine now.
