### ISSUE TITLE
.scatter method does not take lists as input for "s" or "size" parameter

### ISSUE THREAD

**Issue by bockjo** [gmplot/gmplot#20]
Hello, thank you for this amazing library. Very much like the matplotlib interface. I was wondering if there is a way that the .scatter method accepts a list/tuple as input for the "size" parameter.  In matplotlib scatter plots the "s" parameter accepts lists, so that the bubble size can be adjusted for each datapoint. This would also be a great feature for gmplot. Regards, Johannes

**Comment by vgm64** [comment]
That would be a great addition. Would you be interested in coding that up
and submitting a pull request? I might be able to do it, but not
particularly soon. Feel free to poke me about it again if I haven't done
anything in a few weeks.

Michael Woods

**Comment by bockjo** [comment]
`def scatter(self, lats, lngs, sizes, color=None, marker=True, c=None, **kwargs):
        color = color or c
        args["color"] = color
        settings = self._process_kwargs(args)
        #print kwargs
        for lat, lng, size in zip(lats, lngs, sizes):
            if marker:
                self.marker(lat, lng, settings['color'])
            else:
                self.circle(lat, lng, size, **settings)`

**Comment by bockjo** [comment]
`def scatter(self, lats, lngs, sizes, color=None, marker=True, c=None, **kwargs):
        color = color or c
        kwargs["color"] = color
        settings = self._process_kwargs(kwargs)
        for lat, lng, size in zip(lats, lngs, sizes):
            if marker:
                self.marker(lat, lng, settings['color'])
            else:
                self.circle(lat, lng, size, **settings)`
