### ISSUE TITLE
text display at given GPS coordinates

### ISSUE THREAD

**Issue by shawxiaozhang** [gmplot/gmplot#36]
Is it possible to display text at given GPS coordinates?

**Comment by ryanhalabi** [comment]
I just submitted a pull request that addresses this.

**Comment by bishnubhatta** [comment]
**_Note: I am a novice in Python_**

I had similar requirement and I modified the scatter function to add titles as follows:
    def scatter(self, lats, lngs, color=None, size=None, marker=True, c=None,titles=None, s=None, **kwargs):
        color = color or c
        size = size or s or 40
        kwargs["color"] = color
        kwargs["size"] = size
        settings = self._process_kwargs(kwargs)
        if titles==None:
            titles = ["no implementation"]*len(lats)
        elif len(titles) != len(lats):
            titles = ["no implementation"]*len(lats)
        else:
            titles =titles
        #title_len=len(titles)
        for i in range(len(lats)):
            curr_title=titles[i]
            for lat, lng in zip(lats, lngs):
                if marker:
                    self.marker(lat, lng, settings['color'],title=curr_title)
                else:
                    self.circle(lat, lng, size, **settings)

**Comment by chinmay9** [comment]
This didn't work for me. 
Could anyone help me out?

**Comment by frslm** [comment]
This was just implemented in #40/#163. You can use [`text()`](https://github.com/gmplot/gmplot/wiki/GoogleMapPlotter.text) to display text directly on the map.
