### ISSUE TITLE
Color progression with time

### ISSUE THREAD

**Issue by michalmonday** [gmplot/gmplot#44]
Hi, thanks a lot fo this project, it's very useful. Btw this is more suggestion rather than an issue. So the idea is to create color progression with each coordinate to display the order at which some movement occured. It could be done for example by something like this:

#example of usage
`gmap.scatter(latitudes, longitudes, '#3B0B39', size=40, marker=False, progressive=True) `

#implementation in gmplot
`
    def BuildColor(self, r, g, b):
        newClr = "#"
        for num in [r,g,b]:
            newClr += (hex(num)[2:] if len(hex(num)[2:]) > 1 else "0" + hex(num)[2:])
        return newClr

    def scatter(self, lats, lngs, color=None, size=None, marker=True, c=None, s=None, progressive=False, **kwargs):
        color = color or c
        size = size or s or 40
        kwargs["color"] = color
        kwargs["size"] = size
        settings = self._process_kwargs(kwargs)
        print settings['color']
        counter = 0
        for lat, lng in zip(lats, lngs):
            if progressive == True:
                r = int(255.0 / float(len(lats)) * counter)
                g = int(255.0 - (255.0 / float(len(lats)) * counter))
                b = 0
                counter+=1
                settings['color'] = self.BuildColor(r,g,b)
                #print r, g, b
                #print settings['color']
            if marker:
                self.marker(lat, lng, settings['color'])
            else:
                self.circle(lat, lng, size, **settings)`

I edited the gmplot myself (I know it's not perfect :P especially that it's just "green -> red" and making the original color setting useless) but it would be cool if something like this was available in further updates.

**Comment by frslm** [comment]
@michalmonday with the changes made in #152, you can now control the colour of each point separately. So for your scenario, you can define a list of colours that you want (manually or with the help of a library) then just pass that into [`scatter()`](https://github.com/gmplot/gmplot/wiki/GoogleMapPlotter.scatter):

```python3
import gmplot
import math

def build_color(r, g, b):
    color = "#"
    for num in [r, g, b]:    
        color += (hex(num)[2:] if len(hex(num)[2:]) > 1 else "0" + hex(num)[2:])
    return color

def get_color_progression(start_color, end_color, num_points):
    color_delta = []
    for channel in range(3):
        delta = end_color[channel] - start_color[channel]
        if delta >= 0:
            delta = math.floor(delta)
        else:
            delta = math.ceil(delta)

        color_delta.append(int(delta / num_points))

    return [build_color(start_color[0] + color_delta[0] * i, 
                        start_color[1] + color_delta[1] * i,
                        start_color[2] + color_delta[2] * i) for i in range(num_points)]

apikey = '' # (your API key here)

start_lat = 37.766956
start_lng = -122.479481
gmap = gmplot.GoogleMapPlotter(start_lat, start_lng, 13, apikey=apikey)

NUM_POINTS = 50
lats = [start_lat + 0.001 * i for i in range(NUM_POINTS)]
lngs = [start_lng + 0.001 * i for i in range(NUM_POINTS)]

start_color = (0, 255, 0)
end_color = (255, 0, 0)
color = get_color_progression(start_color, end_color, NUM_POINTS)

gmap.scatter(lats, lngs, marker=False, color=color)
gmap.draw('map.html')
```

![image](https://user-images.githubusercontent.com/8406475/84604872-19723100-ae67-11ea-9b97-855f36e2a7c0.png)
