### ISSUE TITLE
contributing code examples pls

### ISSUE THREAD

**Issue by drbhatt** [gmplot/gmplot#45]
Hello there,
This project was helpful in completing an assignment using gmplot to plot various specific coordinates and it was quite simple and easy to follow; here's an working example
https://github.com/drbhatt/gmplot_example

Appreciated your help and support.
Thanks.

**Comment by cwithrow** [comment]
Thanks for sharing- I actually need to plot data in Austin so this should be perfect!

**Comment by frslm** [comment]
Thank you! I've just updated our [Wiki](https://github.com/gmplot/gmplot/wiki) with plenty of code examples, so hopefully it should be easier to work with gmplot.
