### ISSUE TITLE
Pin Dropping

### ISSUE THREAD

**Issue by amiref** [gmplot/gmplot#53]
Is it possible to drop pins by using this library? If yes, how is it possible?

**Comment by vgm64** [comment]
Do you mean on load have all the pins drop in an animated fashion? Or a
click-causes-a-new-pin type of thing? Either way, the answer is probably
no, it's not supported. There are currently no hooks for render time logic.
I'd take a look at the Javascript docs for Maps API and link what
Javascript you'd need to call in this thread and we can chat about whether
it's be feasible to include.

**Comment by frslm** [comment]
You can now drop pins in v1.4.0 using [`enable_marker_dropping()`](https://github.com/gmplot/gmplot/wiki/GoogleMapPlotter.enable_marker_dropping).
