### ISSUE TITLE
add a link to GMaps visualization lib

### ISSUE THREAD

**Issue by sandrotosi** [gmplot/gmplot#6]
https://developers.google.com/maps/documentation/javascript/visualization contains a rich set of information (and it's what gmplot uses) so maybe add a link to it in the readme? f.e. it contains all the description for the class parameters

**Comment by frslm** [comment]
With the changes made in #162, the [Wiki](https://github.com/gmplot/gmplot/wiki) now contains code examples and links to relevant Google Maps documentation (where applicable).
