### ISSUE TITLE
Draw cannot return raw html. Incorrect description.

### ISSUE THREAD

**Issue by Thronics** [gmplot/gmplot#68]
Description of 'draw' says:

- Create the html file which include one google map and all points and paths. **If no string is provided, return the raw html.**

This does not match the the actual code. Not providing a string results in a crash.

**Comment by vgm64** [comment]
You're right. See #66 for context. I'll update either the docs to reflect the current state or re-introduce the feature at some point.

**Comment by frslm** [comment]
The description was updated in #138.

Returning a string instead of writing to a file will be tackled in #108.
