### ISSUE TITLE
Should use matplotlib marker names internally for consistency.

### ISSUE THREAD

**Issue by vgm64** [gmplot/gmplot#69]
When merging new scatter plot types, I realize that we refer to them as CIRCLE, XMARK, and CROSS whereas matplotlib would refer to them as "circle", "x", and "plus". For clarity, they should be renamed internally to CIRCLE_MARKER, X_MARKER, PLUS_MARKER. These aren't really exposed to the public api, so it should be backwards compatible. @OmriRoames 

https://matplotlib.org/api/markers_api.html

**Comment by frslm** [comment]
Fixed in #113.
