### ISSUE TITLE
Sample Code won't work

### ISSUE THREAD

**Issue by ZapDos7** [gmplot/gmplot#72]
After executing exactly what your mini-tutorial/sample code does, I get the error `NameError: global name 'centerLat' is not defined` but there's no such variable in the code. How is this fixed?

**Comment by frslm** [comment]
Hey @ZapDos7 could you attach your produced HTML file here?

**Comment by frslm** [comment]
I'll be closing this for now since I wasn't able to reproduce this and couldn't find an HTML file that shows this issue.

If it happens again, feel free to post your code or a problematic HTML file and I can reopen this.
