### ISSUE TITLE
Strange vertical line appears in my map

### ISSUE THREAD

**Issue by wyzhang24** [gmplot/gmplot#74]
Hi,

I hope somebody can help me. When I plot multiple data by using gmat.plot. The center of gmat is Ann Arbor. But the map generated has some strange straight line. No matter how to zoom in or zoom out, I can still not find the boundary of them. If somebody can answer my question, I will more than appreciate. Thank you!

![image](https://user-images.githubusercontent.com/35239596/40155188-4a99dad4-5960-11e8-9f5f-59fc8c54252f.png)

![image](https://user-images.githubusercontent.com/35239596/40155171-3aee08ee-5960-11e8-8364-c84ec70b89df.png)

**Comment by vgm64** [comment]
Can you provide code to reproduce the issue? Otherwise help will likely be
misguided.

**Comment by wyzhang24** [comment]
Thank you so much for your reply. I have found out the reason. Some of the data is wrong. I think that's the problem of the GPS sensor we used to collect the data. 

Now I meet another problem. I want to save my data as dot by using gmat.scatter. But the file is too large to open. The browser will get stuck and have no response.  I can open the html if I save the data as line by using gmat.plot. But I still want to save the data as dots. I think that because my data is  large. I have more than 4000 trajectories data. Is there any way to solve this problem? 

Thank you!

**Comment by vgm64** [comment]
I would try toggling plotting with markers versus small circles via the
markers keyword option. Or use a heat map instead of individual points.

**Comment by vgm64** [comment]
If you aren't using markers, then the dots are actually made out of many
small lines. If each dot is 25(?) lines then there is 25x more data.
Apparently that is too much!

**Comment by wyzhang24** [comment]
Got you! Thanks for your explanation. The last question, would you mind telling me how to plot the markers as small circles? I didn't find the related examples about that. The example in the main page just generates one marker by using gmap.marker. And I tried to use gmap.scatter with marker=Truth to generate a lot of markers. But I don't know how to change the shape and size of the markers. Sorry for the stupid question, I'm an absolutely rookie in python. I'm more than appreciate for your help. Thank you!

**Comment by vgm64** [comment]
I'm not sure about that off the top of my head (changes have been made
recently). I'd check the source code.

**Comment by wyzhang24** [comment]
Sure. Thank you anyway. You can tell me about that any time when you free. Thank you so much.

**Comment by frslm** [comment]
@wyzhang24 I know this is really late, but just for closure, there now is a [`scatter()`](https://github.com/gmplot/gmplot/wiki/GoogleMapPlotter.scatter) page that shows how to use it.
