### ISSUE TITLE
How do you actually use heatmap.

### ISSUE THREAD

**Issue by bfayers** [gmplot/gmplot#86]
I would like to use heatmap however there is no proper documentation

**Comment by aSipiere** [comment]
@bfayers Also just a heads up, threshold isn't used on the gmaps api, and maxIntensity isn't implemented in a released version yet (you're fine if you've installed from the master branch, but not if you've installed release 1.2).

The current work around I have is a script that edits the maxIntensity settings at the end of the html file after the map is drawn.

**Comment by sriharsha0806** [comment]
@aSipiere link ain't working mate

**Comment by aSipiere** [comment]
@sriharsha0806 Sorry the site changed the link on me. [Here](https://eatsleepdata.com/how-to-generate-a-geographical-heatmap-with-python).

**Comment by aSipiere** [comment]
Also this repo hasn't aged well and isn't really supported anymore. The new google maps api changes also mean that you will almost always get maps with "for development purposes only" watermarks on them.

I've recently moved back to matplotlib for geospatial plots.

**Comment by vgm64** [comment]
The API key requirements should have been solved in #23 2 years ago. I noted somewhat recently that `from_geocode` didn't get API key support and should have.

**Comment by frslm** [comment]
I've just added (in #162) documentation and examples for each of the public functions to our Wiki, which includes [`heatmap()`](https://github.com/gmplot/gmplot/wiki/GoogleMapPlotter.heatmap).

Note that the documentation currently reflects the latest commit, so there might be a few differences until we release the next version, but this should good enough to begin with.
