### ISSUE TITLE
Pins don't get placed on Windwows

### ISSUE THREAD

**Issue by TrueDoctor** [gmplot/gmplot#97]
The Path describing the icon location in the generated html document contains a mix of \ and / wich confuses the Webbrowser.

**Comment by TrueDoctor** [comment]
this could be fixed in a rather dirt way, by manually replacing the backslashes in the String with forward facing slashes like so:
self.coloricon = os.path.join(os.path.dirname(__file__), 'markers/%s.png').replace('\\', '/'))
but there might be an more elegant way to do this

**Comment by frslm** [comment]
Duplicate of #18.
